### ISSUE TITLE
How upload translation file?

### ISSUE THREAD

**Issue by simonbcn** [madmurphy/nautilus-hide#2]
I have done the Spanish translation but I don't know how upload it to you.

**Comment by madmurphy** [comment]
Thank you Simón. The ideal is that you open a pull request, in this way your name will appear among the project's contributors. Another alternative is that you attach the `.po` file to this discussion, but then your name won't appear among the project's contributions (it will still appear in the `.po` file).

--madmurphy

**Comment by simonbcn** [comment]
[es.zip](https://github.com/madmurphy/nautilus-hide/files/10365842/es.zip)

**Comment by madmurphy** [comment]
Thank you. I will upload it in the next days.

--madmurphy
